"""add phone number

Revision ID: 4cbc479880b7
Revises: 970461fd338e
Create Date: 2024-03-10 12:20:25.933014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbc479880b7'
down_revision: Union[str, None] = '970461fd338e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))



def downgrade() -> None:

    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
